# (c) Srevin Saju 2020. All rights reserved 
# Licensed under MIT License
# Continuous Integration to release configured AppImages for Altus

name: Continuous

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*"

jobs:
  Debian:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Current Directory Structure
        run: |
          ls 
          git describe --tags --always
      
      - name: Build Altus
        run: |
          yarn install
          yarn run svelte-build
          yarn add electron-builder --dev
          yarn run electron-builder -l deb --publish never
          mv dist/*.deb altus_amd64.deb

      - name: Upload Debian
        uses: actions/upload-artifact@v1.0.0
        with:
          name: altus_amd64.deb
          path: 'dist/'
  Release:
    needs: [Debian]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2

    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.1.0
      with:
        prerelease: false
        files: |
          altus_amd64.deb

        repo_token: ${{ secrets.GITHUB_TOKEN }}
 
